### ISSUE TITLE
E-prime linting doesn’t support smart quotes

### ISSUE THREAD

**Issue by RichardLitt** [Vorror/e-prime#1]
From @hilton, at https://github.com/btford/write-good/issues/79:

E-prime linting doesn’t report errors for words including _to be_ that use contractions containing curly/smart/typographer’s quotations marks.

To reproduce:

1. enable E-prime linting (Settings / Additional arguments / `--yes-eprime`)
2. save a document containing the words `isn’t isn't`

Expected: both words trigger the `is a form of 'to be'` linting error/warning.

Observed: `isn’t` doesn’t result in an error.

**Comment by Vorror** [comment]
Thanks, I'll make a fix in a day or so.

**Comment by Vorror** [comment]
@RichardLitt I've made the needed changes. Do you mind upgrading your package json to version 0.10.2 ?

**Comment by RichardLitt** [comment]
Done. Thank you!
