### ISSUE TITLE
"It's" missing?

### ISSUE THREAD

**Issue by tomato42** [Vorror/e-prime#2]
I see "is", "isn't", "she's" in the listing:
https://github.com/Vorror/e-prime/blob/894746fd263305333c2fceb738e755455e7c082a/e-prime.js#L13-L15
same for "he's"

But I don't see "it's". Is it an omission or am I missing something?

**Comment by Vorror** [comment]
@tomato42 You're correct. The omission of "it's" is an oversight on my part. I'll deploy a fix today.
