### ISSUE TITLE
LICENSE file in release tarball is somehow broken

### ISSUE THREAD

**Issue by priv-kweihmann** [Vorror/e-prime#3]
In the current release tarball https://registry.npmjs.org/e-prime/-/e-prime-0.10.3.tgz the LICENSE file is name ' LICENSE' instead of 'LICENSE' - making it a bit difficult to address this file properly

**Comment by Vorror** [comment]
Fixed in 0.10.4

**Comment by priv-kweihmann** [comment]
Whoa that was quick - thanks

**Comment by Vorror** [comment]
No problem. Out of curiosity, what issue could this be causing for you?

**Comment by priv-kweihmann** [comment]
I'm playing around with [yocto](https://www.yoctoproject.org/) and npm packages and somehow your package was in the dependency tree - and as yocto insists on proper license files it returned an error, as it's not dealing well with spaces in file names
